function [fitresult, gof] = createFit(t, column3)
%CREATEFIT(T,COLUMN3)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : t
%      Y Output: column3
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 07-Feb-2019 13:11:39


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( t, column3 );

% Set up fittype and options.
ft = fittype( '1 - exp(-a*x)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = 0.44815932576649;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
%figure( 'Name', 'untitled fit 1' );
%h = plot( fitresult, xData, yData );
%legend( h, 'column3 vs. t', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
%xlabel t
%ylabel column3
%grid on


